/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GeracaoDeDemandaRouteImport } from './routes/geracao-de-demanda'
import { Route as MarcaPresencaDigitalRouteImport } from './routes/marca-presenca-digital'
import { Route as RelacionamentoRetencaoRouteImport } from './routes/relacionamento-retencao'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as CasesSlugRouteImport } from './routes/cases.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GeracaoDeDemandaRoute = GeracaoDeDemandaRouteImport.update({
  id: '/geracao-de-demanda',
  path: '/geracao-de-demanda',
  getParentRoute: () => rootRouteImport,
} as any)
const MarcaPresencaDigitalRoute = MarcaPresencaDigitalRouteImport.update({
  id: '/marca-presenca-digital',
  path: '/marca-presenca-digital',
  getParentRoute: () => rootRouteImport,
} as any)
const RelacionamentoRetencaoRoute = RelacionamentoRetencaoRouteImport.update({
  id: '/relacionamento-retencao',
  path: '/relacionamento-retencao',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesSlugRoute = CasesSlugRouteImport.update({
  id: '/cases/$slug',
  path: '/cases/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/geracao-de-demanda': typeof GeracaoDeDemandaRoute
  '/marca-presenca-digital': typeof MarcaPresencaDigitalRoute
  '/relacionamento-retencao': typeof RelacionamentoRetencaoRoute
  '/sobre': typeof SobreRoute
  '/cases/$slug': typeof CasesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/geracao-de-demanda': typeof GeracaoDeDemandaRoute
  '/marca-presenca-digital': typeof MarcaPresencaDigitalRoute
  '/relacionamento-retencao': typeof RelacionamentoRetencaoRoute
  '/sobre': typeof SobreRoute
  '/cases/$slug': typeof CasesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/geracao-de-demanda': typeof GeracaoDeDemandaRoute
  '/marca-presenca-digital': typeof MarcaPresencaDigitalRoute
  '/relacionamento-retencao': typeof RelacionamentoRetencaoRoute
  '/sobre': typeof SobreRoute
  '/cases/$slug': typeof CasesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/geracao-de-demanda'
    | '/marca-presenca-digital'
    | '/relacionamento-retencao'
    | '/sobre'
    | '/cases/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/geracao-de-demanda'
    | '/marca-presenca-digital'
    | '/relacionamento-retencao'
    | '/sobre'
    | '/cases/$slug'
  id:
    | '__root__'
    | '/'
    | '/geracao-de-demanda'
    | '/marca-presenca-digital'
    | '/relacionamento-retencao'
    | '/sobre'
    | '/cases/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GeracaoDeDemandaRoute: typeof GeracaoDeDemandaRoute
  MarcaPresencaDigitalRoute: typeof MarcaPresencaDigitalRoute
  RelacionamentoRetencaoRoute: typeof RelacionamentoRetencaoRoute
  SobreRoute: typeof SobreRoute
  CasesSlugRoute: typeof CasesSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/geracao-de-demanda': {
      id: '/geracao-de-demanda'
      path: '/geracao-de-demanda'
      fullPath: '/geracao-de-demanda'
      preLoaderRoute: typeof GeracaoDeDemandaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marca-presenca-digital': {
      id: '/marca-presenca-digital'
      path: '/marca-presenca-digital'
      fullPath: '/marca-presenca-digital'
      preLoaderRoute: typeof MarcaPresencaDigitalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relacionamento-retencao': {
      id: '/relacionamento-retencao'
      path: '/relacionamento-retencao'
      fullPath: '/relacionamento-retencao'
      preLoaderRoute: typeof RelacionamentoRetencaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/$slug': {
      id: '/cases/$slug'
      path: '/cases/$slug'
      fullPath: '/cases/$slug'
      preLoaderRoute: typeof CasesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GeracaoDeDemandaRoute: GeracaoDeDemandaRoute,
  MarcaPresencaDigitalRoute: MarcaPresencaDigitalRoute,
  RelacionamentoRetencaoRoute: RelacionamentoRetencaoRoute,
  SobreRoute: SobreRoute,
  CasesSlugRoute: CasesSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
